### ISSUE TITLE
Needs to be greedy

### ISSUE THREAD

**Issue by ralyodio** [Cordobo/rollup-plugin-replace-html-vars#4]
ONly replaces first instance of FOO

**Comment by Cordobo** [comment]
Did you try the following part of the readme?
https://github.com/Cordobo/rollup-plugin-replace-html-vars#regular-expressions-and-easy-cache-buster

That should fix your issue. Closing, please reopen if it won't work for you, please add a link to a repository on github where I can reproduce the issue. Thanks
